### ISSUE TITLE
Mixing runtimes

### ISSUE THREAD

**Issue by agg23** [ryanmcgrath/cacao#96]
I'm interested in how others may have mixed the AppKit runtime with something Rust-centric, whether `async-std`, `tokio`, or something else. Use cases are primarily in mixed platform systems, the core Rust code can't be designed around the standard Apple runtime, and needs something from the Rust ecosystem to actually be usable.

I have found that naively calling `NSApplication.run()` within `tokio::task::spawn_blocking` results in the event loop hanging.

**Comment by ryanmcgrath** [comment]
Hmmm, can you throw together a repo or test case? It's probably a straightforward (as you say) case, but I've run `async-std` in the background of a cacao app without any issues. It _should_ work so I'm wondering if there's something I'm missing.

(I was building a magic-wormhole for macOS app before I got... sidetracked... by life, lol: https://twitter.com/ryanmcgrath/status/1657967789142069249)

**Comment by agg23** [comment]
Most likely it's my inexperience with Rust runtimes (including Tokio), but here's a simple example of Tokio functioning normally, but nothing happening from AppKit:

```rust
use std::time::Duration;

use cacao::appkit::{App, AppDelegate};

struct MacApp;

impl AppDelegate for MacApp {
    fn did_finish_launching(&self) {
        println!("AppKit running");
    }
}

#[tokio::main]
async fn main() {
    tokio::task::spawn(async {
        loop {
            tokio::time::sleep(Duration::from_secs(1)).await;

            println!("Timer");
        }
    });

    println!("Starting AppKit");

    tokio::task::spawn_blocking(|| {
        App::new("com.example.cacao_runtime", MacApp).run();
    });

    println!("After AppKit");

    // We await this to keep the runtime alive/in scope
    let _ = tokio::task::spawn_blocking(|| {
        let mut spin_count: u128 = 0;

        loop {
            if spin_count % 100_000_000 == 0 {
                println!("Tick");
            }

            spin_count += 1;
        }
    })
    .await;
}
```

```toml
[package]
name = "cacao_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cacao = "0.3.2"
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros", "time"] }
```

Expected output would be something like:

```
Starting AppKit
After AppKit
AppKit running
Tick
Tick
Tick
Tick
Tick
Tick
Timer
Tick
Tick
```

but what we actually get is:
```
Starting AppKit
After AppKit
Tick
Tick
Tick
Tick
Tick
Tick
Timer
Tick
Tick
```

That is, just missing the `applicationDidFinishLaunching` callback. I've tried stepping through to see where it is getting hung up, but as you know debugging Rust _and_ mixing that with weird Obj-C bridging makes it difficult to tell.
